/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthResetPasswordRouteImport } from "./routes/auth/reset-password";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthLogoutRouteImport } from "./routes/auth/logout";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth/forgot-password";
import { Route as AuthedReportsRouteImport } from "./routes/_authed/reports";
import { Route as AuthedAppRouteImport } from "./routes/_authed/app";
import { Route as AuthedAdminRouteImport } from "./routes/_authed/admin";
import { Route as ApiSetupStatusIndexRouteImport } from "./routes/api/setup-status/index";
import { Route as ApiOgIndexRouteImport } from "./routes/api/og/index";
import { Route as ApiManifestIndexRouteImport } from "./routes/api/manifest/index";
import { Route as AuthedReportsIndexRouteImport } from "./routes/_authed/reports/index";
import { Route as AuthedAppIndexRouteImport } from "./routes/_authed/app/index";
import { Route as AuthedAdminIndexRouteImport } from "./routes/_authed/admin/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as AuthedAppNewRouteImport } from "./routes/_authed/app/new";
import { Route as AuthedAppBrandRouteImport } from "./routes/_authed/app/$brand";
import { Route as AuthedAdminWorkflowsRouteImport } from "./routes/_authed/admin/workflows";
import { Route as AuthedAdminToolsRouteImport } from "./routes/_authed/admin/tools";
import { Route as AuthedAcceptInvitationInvitationIdRouteImport } from "./routes/_authed/accept-invitation/$invitationId";
import { Route as ApiV1ReportsIndexRouteImport } from "./routes/api/v1/reports/index";
import { Route as ApiV1PromptsIndexRouteImport } from "./routes/api/v1/prompts/index";
import { Route as ApiV1DocsIndexRouteImport } from "./routes/api/v1/docs/index";
import { Route as ApiV1CompetitorsIndexRouteImport } from "./routes/api/v1/competitors/index";
import { Route as ApiV1BrandsIndexRouteImport } from "./routes/api/v1/brands/index";
import { Route as ApiPlausibleEventIndexRouteImport } from "./routes/api/plausible/event/index";
import { Route as AuthedAppBrandIndexRouteImport } from "./routes/_authed/app/$brand/index";
import { Route as ApiV1ToolsAnalyzeRouteImport } from "./routes/api/v1/tools/analyze";
import { Route as ApiV1ReportsReportIdRouteImport } from "./routes/api/v1/reports/$reportId";
import { Route as ApiV1PromptsPromptIdRouteImport } from "./routes/api/v1/prompts/$promptId";
import { Route as ApiV1CompetitorsCompetitorIdRouteImport } from "./routes/api/v1/competitors/$competitorId";
import { Route as ApiV1BrandsBrandIdRouteImport } from "./routes/api/v1/brands/$brandId";
import { Route as AuthedReportsRenderReportIdRouteImport } from "./routes/_authed/reports/render/$reportId";
import { Route as AuthedAppBrandVisibilityRouteImport } from "./routes/_authed/app/$brand/visibility";
import { Route as AuthedAppBrandShareOfVoiceRouteImport } from "./routes/_authed/app/$brand/share-of-voice";
import { Route as AuthedAppBrandQueryFanOutRouteImport } from "./routes/_authed/app/$brand/query-fan-out";
import { Route as AuthedAppBrandOpportunitiesRouteImport } from "./routes/_authed/app/$brand/opportunities";
import { Route as AuthedAppBrandCitationsRouteImport } from "./routes/_authed/app/$brand/citations";
import { Route as AuthedAppBrandSplatRouteImport } from "./routes/_authed/app/$brand/$";
import { Route as ApiPlausibleJsScriptIndexRouteImport } from "./routes/api/plausible/js/script/index";
import { Route as AuthedAppBrandSettingsIndexRouteImport } from "./routes/_authed/app/$brand/settings/index";
import { Route as AuthedAppBrandPromptsIndexRouteImport } from "./routes/_authed/app/$brand/prompts/index";
import { Route as ApiV1PromptsPromptIdSnapshotRouteImport } from "./routes/api/v1/prompts/$promptId/snapshot";
import { Route as AuthedAppBrandSettingsPromptsRouteImport } from "./routes/_authed/app/$brand/settings/prompts";
import { Route as AuthedAppBrandSettingsMembersRouteImport } from "./routes/_authed/app/$brand/settings/members";
import { Route as AuthedAppBrandSettingsLlmsRouteImport } from "./routes/_authed/app/$brand/settings/llms";
import { Route as AuthedAppBrandSettingsCompetitorsRouteImport } from "./routes/_authed/app/$brand/settings/competitors";
import { Route as AuthedAppBrandSettingsBrandRouteImport } from "./routes/_authed/app/$brand/settings/brand";
import { Route as AuthedAppBrandPromptsEditRouteImport } from "./routes/_authed/app/$brand/prompts/edit";
import { Route as AuthedAppBrandPromptsPromptIdRouteImport } from "./routes/_authed/app/$brand/prompts/$promptId";

const AuthedRoute = AuthedRouteImport.update({
	id: "/_authed",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
	id: "/auth/reset-password",
	path: "/auth/reset-password",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
	id: "/auth/register",
	path: "/auth/register",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthLogoutRoute = AuthLogoutRouteImport.update({
	id: "/auth/logout",
	path: "/auth/logout",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
	id: "/auth/login",
	path: "/auth/login",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
	id: "/auth/forgot-password",
	path: "/auth/forgot-password",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthedReportsRoute = AuthedReportsRouteImport.update({
	id: "/reports",
	path: "/reports",
	getParentRoute: () => AuthedRoute,
} as any);
const AuthedAppRoute = AuthedAppRouteImport.update({
	id: "/app",
	path: "/app",
	getParentRoute: () => AuthedRoute,
} as any);
const AuthedAdminRoute = AuthedAdminRouteImport.update({
	id: "/admin",
	path: "/admin",
	getParentRoute: () => AuthedRoute,
} as any);
const ApiSetupStatusIndexRoute = ApiSetupStatusIndexRouteImport.update({
	id: "/api/setup-status/",
	path: "/api/setup-status/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
	id: "/api/og/",
	path: "/api/og/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiManifestIndexRoute = ApiManifestIndexRouteImport.update({
	id: "/api/manifest/",
	path: "/api/manifest/",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthedReportsIndexRoute = AuthedReportsIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => AuthedReportsRoute,
} as any);
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => AuthedAppRoute,
} as any);
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => AuthedAdminRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
	id: "/api/auth/$",
	path: "/api/auth/$",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthedAppNewRoute = AuthedAppNewRouteImport.update({
	id: "/new",
	path: "/new",
	getParentRoute: () => AuthedAppRoute,
} as any);
const AuthedAppBrandRoute = AuthedAppBrandRouteImport.update({
	id: "/$brand",
	path: "/$brand",
	getParentRoute: () => AuthedAppRoute,
} as any);
const AuthedAdminWorkflowsRoute = AuthedAdminWorkflowsRouteImport.update({
	id: "/workflows",
	path: "/workflows",
	getParentRoute: () => AuthedAdminRoute,
} as any);
const AuthedAdminToolsRoute = AuthedAdminToolsRouteImport.update({
	id: "/tools",
	path: "/tools",
	getParentRoute: () => AuthedAdminRoute,
} as any);
const AuthedAcceptInvitationInvitationIdRoute = AuthedAcceptInvitationInvitationIdRouteImport.update({
	id: "/accept-invitation/$invitationId",
	path: "/accept-invitation/$invitationId",
	getParentRoute: () => AuthedRoute,
} as any);
const ApiV1ReportsIndexRoute = ApiV1ReportsIndexRouteImport.update({
	id: "/api/v1/reports/",
	path: "/api/v1/reports/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiV1PromptsIndexRoute = ApiV1PromptsIndexRouteImport.update({
	id: "/api/v1/prompts/",
	path: "/api/v1/prompts/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiV1DocsIndexRoute = ApiV1DocsIndexRouteImport.update({
	id: "/api/v1/docs/",
	path: "/api/v1/docs/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiV1CompetitorsIndexRoute = ApiV1CompetitorsIndexRouteImport.update({
	id: "/api/v1/competitors/",
	path: "/api/v1/competitors/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiV1BrandsIndexRoute = ApiV1BrandsIndexRouteImport.update({
	id: "/api/v1/brands/",
	path: "/api/v1/brands/",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiPlausibleEventIndexRoute = ApiPlausibleEventIndexRouteImport.update({
	id: "/api/plausible/event/",
	path: "/api/plausible/event/",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthedAppBrandIndexRoute = AuthedAppBrandIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const ApiV1ToolsAnalyzeRoute = ApiV1ToolsAnalyzeRouteImport.update({
	id: "/api/v1/tools/analyze",
	path: "/api/v1/tools/analyze",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiV1ReportsReportIdRoute = ApiV1ReportsReportIdRouteImport.update({
	id: "/api/v1/reports/$reportId",
	path: "/api/v1/reports/$reportId",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiV1PromptsPromptIdRoute = ApiV1PromptsPromptIdRouteImport.update({
	id: "/api/v1/prompts/$promptId",
	path: "/api/v1/prompts/$promptId",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiV1CompetitorsCompetitorIdRoute = ApiV1CompetitorsCompetitorIdRouteImport.update({
	id: "/api/v1/competitors/$competitorId",
	path: "/api/v1/competitors/$competitorId",
	getParentRoute: () => rootRouteImport,
} as any);
const ApiV1BrandsBrandIdRoute = ApiV1BrandsBrandIdRouteImport.update({
	id: "/api/v1/brands/$brandId",
	path: "/api/v1/brands/$brandId",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthedReportsRenderReportIdRoute = AuthedReportsRenderReportIdRouteImport.update({
	id: "/render/$reportId",
	path: "/render/$reportId",
	getParentRoute: () => AuthedReportsRoute,
} as any);
const AuthedAppBrandVisibilityRoute = AuthedAppBrandVisibilityRouteImport.update({
	id: "/visibility",
	path: "/visibility",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandShareOfVoiceRoute = AuthedAppBrandShareOfVoiceRouteImport.update({
	id: "/share-of-voice",
	path: "/share-of-voice",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandQueryFanOutRoute = AuthedAppBrandQueryFanOutRouteImport.update({
	id: "/query-fan-out",
	path: "/query-fan-out",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandOpportunitiesRoute = AuthedAppBrandOpportunitiesRouteImport.update({
	id: "/opportunities",
	path: "/opportunities",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandCitationsRoute = AuthedAppBrandCitationsRouteImport.update({
	id: "/citations",
	path: "/citations",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandSplatRoute = AuthedAppBrandSplatRouteImport.update({
	id: "/$",
	path: "/$",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const ApiPlausibleJsScriptIndexRoute = ApiPlausibleJsScriptIndexRouteImport.update({
	id: "/api/plausible/js/script/",
	path: "/api/plausible/js/script/",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthedAppBrandSettingsIndexRoute = AuthedAppBrandSettingsIndexRouteImport.update({
	id: "/settings/",
	path: "/settings/",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandPromptsIndexRoute = AuthedAppBrandPromptsIndexRouteImport.update({
	id: "/prompts/",
	path: "/prompts/",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const ApiV1PromptsPromptIdSnapshotRoute = ApiV1PromptsPromptIdSnapshotRouteImport.update({
	id: "/snapshot",
	path: "/snapshot",
	getParentRoute: () => ApiV1PromptsPromptIdRoute,
} as any);
const AuthedAppBrandSettingsPromptsRoute = AuthedAppBrandSettingsPromptsRouteImport.update({
	id: "/settings/prompts",
	path: "/settings/prompts",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandSettingsMembersRoute = AuthedAppBrandSettingsMembersRouteImport.update({
	id: "/settings/members",
	path: "/settings/members",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandSettingsLlmsRoute = AuthedAppBrandSettingsLlmsRouteImport.update({
	id: "/settings/llms",
	path: "/settings/llms",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandSettingsCompetitorsRoute = AuthedAppBrandSettingsCompetitorsRouteImport.update({
	id: "/settings/competitors",
	path: "/settings/competitors",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandSettingsBrandRoute = AuthedAppBrandSettingsBrandRouteImport.update({
	id: "/settings/brand",
	path: "/settings/brand",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandPromptsEditRoute = AuthedAppBrandPromptsEditRouteImport.update({
	id: "/prompts/edit",
	path: "/prompts/edit",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);
const AuthedAppBrandPromptsPromptIdRoute = AuthedAppBrandPromptsPromptIdRouteImport.update({
	id: "/prompts/$promptId",
	path: "/prompts/$promptId",
	getParentRoute: () => AuthedAppBrandRoute,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/admin": typeof AuthedAdminRouteWithChildren;
	"/app": typeof AuthedAppRouteWithChildren;
	"/reports": typeof AuthedReportsRouteWithChildren;
	"/auth/forgot-password": typeof AuthForgotPasswordRoute;
	"/auth/login": typeof AuthLoginRoute;
	"/auth/logout": typeof AuthLogoutRoute;
	"/auth/register": typeof AuthRegisterRoute;
	"/auth/reset-password": typeof AuthResetPasswordRoute;
	"/accept-invitation/$invitationId": typeof AuthedAcceptInvitationInvitationIdRoute;
	"/admin/tools": typeof AuthedAdminToolsRoute;
	"/admin/workflows": typeof AuthedAdminWorkflowsRoute;
	"/app/$brand": typeof AuthedAppBrandRouteWithChildren;
	"/app/new": typeof AuthedAppNewRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
	"/admin/": typeof AuthedAdminIndexRoute;
	"/app/": typeof AuthedAppIndexRoute;
	"/reports/": typeof AuthedReportsIndexRoute;
	"/api/manifest/": typeof ApiManifestIndexRoute;
	"/api/og/": typeof ApiOgIndexRoute;
	"/api/setup-status/": typeof ApiSetupStatusIndexRoute;
	"/app/$brand/$": typeof AuthedAppBrandSplatRoute;
	"/app/$brand/citations": typeof AuthedAppBrandCitationsRoute;
	"/app/$brand/opportunities": typeof AuthedAppBrandOpportunitiesRoute;
	"/app/$brand/query-fan-out": typeof AuthedAppBrandQueryFanOutRoute;
	"/app/$brand/share-of-voice": typeof AuthedAppBrandShareOfVoiceRoute;
	"/app/$brand/visibility": typeof AuthedAppBrandVisibilityRoute;
	"/reports/render/$reportId": typeof AuthedReportsRenderReportIdRoute;
	"/api/v1/brands/$brandId": typeof ApiV1BrandsBrandIdRoute;
	"/api/v1/competitors/$competitorId": typeof ApiV1CompetitorsCompetitorIdRoute;
	"/api/v1/prompts/$promptId": typeof ApiV1PromptsPromptIdRouteWithChildren;
	"/api/v1/reports/$reportId": typeof ApiV1ReportsReportIdRoute;
	"/api/v1/tools/analyze": typeof ApiV1ToolsAnalyzeRoute;
	"/app/$brand/": typeof AuthedAppBrandIndexRoute;
	"/api/plausible/event/": typeof ApiPlausibleEventIndexRoute;
	"/api/v1/brands/": typeof ApiV1BrandsIndexRoute;
	"/api/v1/competitors/": typeof ApiV1CompetitorsIndexRoute;
	"/api/v1/docs/": typeof ApiV1DocsIndexRoute;
	"/api/v1/prompts/": typeof ApiV1PromptsIndexRoute;
	"/api/v1/reports/": typeof ApiV1ReportsIndexRoute;
	"/app/$brand/prompts/$promptId": typeof AuthedAppBrandPromptsPromptIdRoute;
	"/app/$brand/prompts/edit": typeof AuthedAppBrandPromptsEditRoute;
	"/app/$brand/settings/brand": typeof AuthedAppBrandSettingsBrandRoute;
	"/app/$brand/settings/competitors": typeof AuthedAppBrandSettingsCompetitorsRoute;
	"/app/$brand/settings/llms": typeof AuthedAppBrandSettingsLlmsRoute;
	"/app/$brand/settings/members": typeof AuthedAppBrandSettingsMembersRoute;
	"/app/$brand/settings/prompts": typeof AuthedAppBrandSettingsPromptsRoute;
	"/api/v1/prompts/$promptId/snapshot": typeof ApiV1PromptsPromptIdSnapshotRoute;
	"/app/$brand/prompts/": typeof AuthedAppBrandPromptsIndexRoute;
	"/app/$brand/settings/": typeof AuthedAppBrandSettingsIndexRoute;
	"/api/plausible/js/script/": typeof ApiPlausibleJsScriptIndexRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/auth/forgot-password": typeof AuthForgotPasswordRoute;
	"/auth/login": typeof AuthLoginRoute;
	"/auth/logout": typeof AuthLogoutRoute;
	"/auth/register": typeof AuthRegisterRoute;
	"/auth/reset-password": typeof AuthResetPasswordRoute;
	"/accept-invitation/$invitationId": typeof AuthedAcceptInvitationInvitationIdRoute;
	"/admin/tools": typeof AuthedAdminToolsRoute;
	"/admin/workflows": typeof AuthedAdminWorkflowsRoute;
	"/app/new": typeof AuthedAppNewRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
	"/admin": typeof AuthedAdminIndexRoute;
	"/app": typeof AuthedAppIndexRoute;
	"/reports": typeof AuthedReportsIndexRoute;
	"/api/manifest": typeof ApiManifestIndexRoute;
	"/api/og": typeof ApiOgIndexRoute;
	"/api/setup-status": typeof ApiSetupStatusIndexRoute;
	"/app/$brand/$": typeof AuthedAppBrandSplatRoute;
	"/app/$brand/citations": typeof AuthedAppBrandCitationsRoute;
	"/app/$brand/opportunities": typeof AuthedAppBrandOpportunitiesRoute;
	"/app/$brand/query-fan-out": typeof AuthedAppBrandQueryFanOutRoute;
	"/app/$brand/share-of-voice": typeof AuthedAppBrandShareOfVoiceRoute;
	"/app/$brand/visibility": typeof AuthedAppBrandVisibilityRoute;
	"/reports/render/$reportId": typeof AuthedReportsRenderReportIdRoute;
	"/api/v1/brands/$brandId": typeof ApiV1BrandsBrandIdRoute;
	"/api/v1/competitors/$competitorId": typeof ApiV1CompetitorsCompetitorIdRoute;
	"/api/v1/prompts/$promptId": typeof ApiV1PromptsPromptIdRouteWithChildren;
	"/api/v1/reports/$reportId": typeof ApiV1ReportsReportIdRoute;
	"/api/v1/tools/analyze": typeof ApiV1ToolsAnalyzeRoute;
	"/app/$brand": typeof AuthedAppBrandIndexRoute;
	"/api/plausible/event": typeof ApiPlausibleEventIndexRoute;
	"/api/v1/brands": typeof ApiV1BrandsIndexRoute;
	"/api/v1/competitors": typeof ApiV1CompetitorsIndexRoute;
	"/api/v1/docs": typeof ApiV1DocsIndexRoute;
	"/api/v1/prompts": typeof ApiV1PromptsIndexRoute;
	"/api/v1/reports": typeof ApiV1ReportsIndexRoute;
	"/app/$brand/prompts/$promptId": typeof AuthedAppBrandPromptsPromptIdRoute;
	"/app/$brand/prompts/edit": typeof AuthedAppBrandPromptsEditRoute;
	"/app/$brand/settings/brand": typeof AuthedAppBrandSettingsBrandRoute;
	"/app/$brand/settings/competitors": typeof AuthedAppBrandSettingsCompetitorsRoute;
	"/app/$brand/settings/llms": typeof AuthedAppBrandSettingsLlmsRoute;
	"/app/$brand/settings/members": typeof AuthedAppBrandSettingsMembersRoute;
	"/app/$brand/settings/prompts": typeof AuthedAppBrandSettingsPromptsRoute;
	"/api/v1/prompts/$promptId/snapshot": typeof ApiV1PromptsPromptIdSnapshotRoute;
	"/app/$brand/prompts": typeof AuthedAppBrandPromptsIndexRoute;
	"/app/$brand/settings": typeof AuthedAppBrandSettingsIndexRoute;
	"/api/plausible/js/script": typeof ApiPlausibleJsScriptIndexRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/_authed": typeof AuthedRouteWithChildren;
	"/_authed/admin": typeof AuthedAdminRouteWithChildren;
	"/_authed/app": typeof AuthedAppRouteWithChildren;
	"/_authed/reports": typeof AuthedReportsRouteWithChildren;
	"/auth/forgot-password": typeof AuthForgotPasswordRoute;
	"/auth/login": typeof AuthLoginRoute;
	"/auth/logout": typeof AuthLogoutRoute;
	"/auth/register": typeof AuthRegisterRoute;
	"/auth/reset-password": typeof AuthResetPasswordRoute;
	"/_authed/accept-invitation/$invitationId": typeof AuthedAcceptInvitationInvitationIdRoute;
	"/_authed/admin/tools": typeof AuthedAdminToolsRoute;
	"/_authed/admin/workflows": typeof AuthedAdminWorkflowsRoute;
	"/_authed/app/$brand": typeof AuthedAppBrandRouteWithChildren;
	"/_authed/app/new": typeof AuthedAppNewRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
	"/_authed/admin/": typeof AuthedAdminIndexRoute;
	"/_authed/app/": typeof AuthedAppIndexRoute;
	"/_authed/reports/": typeof AuthedReportsIndexRoute;
	"/api/manifest/": typeof ApiManifestIndexRoute;
	"/api/og/": typeof ApiOgIndexRoute;
	"/api/setup-status/": typeof ApiSetupStatusIndexRoute;
	"/_authed/app/$brand/$": typeof AuthedAppBrandSplatRoute;
	"/_authed/app/$brand/citations": typeof AuthedAppBrandCitationsRoute;
	"/_authed/app/$brand/opportunities": typeof AuthedAppBrandOpportunitiesRoute;
	"/_authed/app/$brand/query-fan-out": typeof AuthedAppBrandQueryFanOutRoute;
	"/_authed/app/$brand/share-of-voice": typeof AuthedAppBrandShareOfVoiceRoute;
	"/_authed/app/$brand/visibility": typeof AuthedAppBrandVisibilityRoute;
	"/_authed/reports/render/$reportId": typeof AuthedReportsRenderReportIdRoute;
	"/api/v1/brands/$brandId": typeof ApiV1BrandsBrandIdRoute;
	"/api/v1/competitors/$competitorId": typeof ApiV1CompetitorsCompetitorIdRoute;
	"/api/v1/prompts/$promptId": typeof ApiV1PromptsPromptIdRouteWithChildren;
	"/api/v1/reports/$reportId": typeof ApiV1ReportsReportIdRoute;
	"/api/v1/tools/analyze": typeof ApiV1ToolsAnalyzeRoute;
	"/_authed/app/$brand/": typeof AuthedAppBrandIndexRoute;
	"/api/plausible/event/": typeof ApiPlausibleEventIndexRoute;
	"/api/v1/brands/": typeof ApiV1BrandsIndexRoute;
	"/api/v1/competitors/": typeof ApiV1CompetitorsIndexRoute;
	"/api/v1/docs/": typeof ApiV1DocsIndexRoute;
	"/api/v1/prompts/": typeof ApiV1PromptsIndexRoute;
	"/api/v1/reports/": typeof ApiV1ReportsIndexRoute;
	"/_authed/app/$brand/prompts/$promptId": typeof AuthedAppBrandPromptsPromptIdRoute;
	"/_authed/app/$brand/prompts/edit": typeof AuthedAppBrandPromptsEditRoute;
	"/_authed/app/$brand/settings/brand": typeof AuthedAppBrandSettingsBrandRoute;
	"/_authed/app/$brand/settings/competitors": typeof AuthedAppBrandSettingsCompetitorsRoute;
	"/_authed/app/$brand/settings/llms": typeof AuthedAppBrandSettingsLlmsRoute;
	"/_authed/app/$brand/settings/members": typeof AuthedAppBrandSettingsMembersRoute;
	"/_authed/app/$brand/settings/prompts": typeof AuthedAppBrandSettingsPromptsRoute;
	"/api/v1/prompts/$promptId/snapshot": typeof ApiV1PromptsPromptIdSnapshotRoute;
	"/_authed/app/$brand/prompts/": typeof AuthedAppBrandPromptsIndexRoute;
	"/_authed/app/$brand/settings/": typeof AuthedAppBrandSettingsIndexRoute;
	"/api/plausible/js/script/": typeof ApiPlausibleJsScriptIndexRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/admin"
		| "/app"
		| "/reports"
		| "/auth/forgot-password"
		| "/auth/login"
		| "/auth/logout"
		| "/auth/register"
		| "/auth/reset-password"
		| "/accept-invitation/$invitationId"
		| "/admin/tools"
		| "/admin/workflows"
		| "/app/$brand"
		| "/app/new"
		| "/api/auth/$"
		| "/admin/"
		| "/app/"
		| "/reports/"
		| "/api/manifest/"
		| "/api/og/"
		| "/api/setup-status/"
		| "/app/$brand/$"
		| "/app/$brand/citations"
		| "/app/$brand/opportunities"
		| "/app/$brand/query-fan-out"
		| "/app/$brand/share-of-voice"
		| "/app/$brand/visibility"
		| "/reports/render/$reportId"
		| "/api/v1/brands/$brandId"
		| "/api/v1/competitors/$competitorId"
		| "/api/v1/prompts/$promptId"
		| "/api/v1/reports/$reportId"
		| "/api/v1/tools/analyze"
		| "/app/$brand/"
		| "/api/plausible/event/"
		| "/api/v1/brands/"
		| "/api/v1/competitors/"
		| "/api/v1/docs/"
		| "/api/v1/prompts/"
		| "/api/v1/reports/"
		| "/app/$brand/prompts/$promptId"
		| "/app/$brand/prompts/edit"
		| "/app/$brand/settings/brand"
		| "/app/$brand/settings/competitors"
		| "/app/$brand/settings/llms"
		| "/app/$brand/settings/members"
		| "/app/$brand/settings/prompts"
		| "/api/v1/prompts/$promptId/snapshot"
		| "/app/$brand/prompts/"
		| "/app/$brand/settings/"
		| "/api/plausible/js/script/";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/auth/forgot-password"
		| "/auth/login"
		| "/auth/logout"
		| "/auth/register"
		| "/auth/reset-password"
		| "/accept-invitation/$invitationId"
		| "/admin/tools"
		| "/admin/workflows"
		| "/app/new"
		| "/api/auth/$"
		| "/admin"
		| "/app"
		| "/reports"
		| "/api/manifest"
		| "/api/og"
		| "/api/setup-status"
		| "/app/$brand/$"
		| "/app/$brand/citations"
		| "/app/$brand/opportunities"
		| "/app/$brand/query-fan-out"
		| "/app/$brand/share-of-voice"
		| "/app/$brand/visibility"
		| "/reports/render/$reportId"
		| "/api/v1/brands/$brandId"
		| "/api/v1/competitors/$competitorId"
		| "/api/v1/prompts/$promptId"
		| "/api/v1/reports/$reportId"
		| "/api/v1/tools/analyze"
		| "/app/$brand"
		| "/api/plausible/event"
		| "/api/v1/brands"
		| "/api/v1/competitors"
		| "/api/v1/docs"
		| "/api/v1/prompts"
		| "/api/v1/reports"
		| "/app/$brand/prompts/$promptId"
		| "/app/$brand/prompts/edit"
		| "/app/$brand/settings/brand"
		| "/app/$brand/settings/competitors"
		| "/app/$brand/settings/llms"
		| "/app/$brand/settings/members"
		| "/app/$brand/settings/prompts"
		| "/api/v1/prompts/$promptId/snapshot"
		| "/app/$brand/prompts"
		| "/app/$brand/settings"
		| "/api/plausible/js/script";
	id:
		| "__root__"
		| "/"
		| "/_authed"
		| "/_authed/admin"
		| "/_authed/app"
		| "/_authed/reports"
		| "/auth/forgot-password"
		| "/auth/login"
		| "/auth/logout"
		| "/auth/register"
		| "/auth/reset-password"
		| "/_authed/accept-invitation/$invitationId"
		| "/_authed/admin/tools"
		| "/_authed/admin/workflows"
		| "/_authed/app/$brand"
		| "/_authed/app/new"
		| "/api/auth/$"
		| "/_authed/admin/"
		| "/_authed/app/"
		| "/_authed/reports/"
		| "/api/manifest/"
		| "/api/og/"
		| "/api/setup-status/"
		| "/_authed/app/$brand/$"
		| "/_authed/app/$brand/citations"
		| "/_authed/app/$brand/opportunities"
		| "/_authed/app/$brand/query-fan-out"
		| "/_authed/app/$brand/share-of-voice"
		| "/_authed/app/$brand/visibility"
		| "/_authed/reports/render/$reportId"
		| "/api/v1/brands/$brandId"
		| "/api/v1/competitors/$competitorId"
		| "/api/v1/prompts/$promptId"
		| "/api/v1/reports/$reportId"
		| "/api/v1/tools/analyze"
		| "/_authed/app/$brand/"
		| "/api/plausible/event/"
		| "/api/v1/brands/"
		| "/api/v1/competitors/"
		| "/api/v1/docs/"
		| "/api/v1/prompts/"
		| "/api/v1/reports/"
		| "/_authed/app/$brand/prompts/$promptId"
		| "/_authed/app/$brand/prompts/edit"
		| "/_authed/app/$brand/settings/brand"
		| "/_authed/app/$brand/settings/competitors"
		| "/_authed/app/$brand/settings/llms"
		| "/_authed/app/$brand/settings/members"
		| "/_authed/app/$brand/settings/prompts"
		| "/api/v1/prompts/$promptId/snapshot"
		| "/_authed/app/$brand/prompts/"
		| "/_authed/app/$brand/settings/"
		| "/api/plausible/js/script/";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	AuthedRoute: typeof AuthedRouteWithChildren;
	AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
	AuthLoginRoute: typeof AuthLoginRoute;
	AuthLogoutRoute: typeof AuthLogoutRoute;
	AuthRegisterRoute: typeof AuthRegisterRoute;
	AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
	ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
	ApiManifestIndexRoute: typeof ApiManifestIndexRoute;
	ApiOgIndexRoute: typeof ApiOgIndexRoute;
	ApiSetupStatusIndexRoute: typeof ApiSetupStatusIndexRoute;
	ApiV1BrandsBrandIdRoute: typeof ApiV1BrandsBrandIdRoute;
	ApiV1CompetitorsCompetitorIdRoute: typeof ApiV1CompetitorsCompetitorIdRoute;
	ApiV1PromptsPromptIdRoute: typeof ApiV1PromptsPromptIdRouteWithChildren;
	ApiV1ReportsReportIdRoute: typeof ApiV1ReportsReportIdRoute;
	ApiV1ToolsAnalyzeRoute: typeof ApiV1ToolsAnalyzeRoute;
	ApiPlausibleEventIndexRoute: typeof ApiPlausibleEventIndexRoute;
	ApiV1BrandsIndexRoute: typeof ApiV1BrandsIndexRoute;
	ApiV1CompetitorsIndexRoute: typeof ApiV1CompetitorsIndexRoute;
	ApiV1DocsIndexRoute: typeof ApiV1DocsIndexRoute;
	ApiV1PromptsIndexRoute: typeof ApiV1PromptsIndexRoute;
	ApiV1ReportsIndexRoute: typeof ApiV1ReportsIndexRoute;
	ApiPlausibleJsScriptIndexRoute: typeof ApiPlausibleJsScriptIndexRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/_authed": {
			id: "/_authed";
			path: "";
			fullPath: "/";
			preLoaderRoute: typeof AuthedRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/auth/reset-password": {
			id: "/auth/reset-password";
			path: "/auth/reset-password";
			fullPath: "/auth/reset-password";
			preLoaderRoute: typeof AuthResetPasswordRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/auth/register": {
			id: "/auth/register";
			path: "/auth/register";
			fullPath: "/auth/register";
			preLoaderRoute: typeof AuthRegisterRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/auth/logout": {
			id: "/auth/logout";
			path: "/auth/logout";
			fullPath: "/auth/logout";
			preLoaderRoute: typeof AuthLogoutRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/auth/login": {
			id: "/auth/login";
			path: "/auth/login";
			fullPath: "/auth/login";
			preLoaderRoute: typeof AuthLoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/auth/forgot-password": {
			id: "/auth/forgot-password";
			path: "/auth/forgot-password";
			fullPath: "/auth/forgot-password";
			preLoaderRoute: typeof AuthForgotPasswordRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authed/reports": {
			id: "/_authed/reports";
			path: "/reports";
			fullPath: "/reports";
			preLoaderRoute: typeof AuthedReportsRouteImport;
			parentRoute: typeof AuthedRoute;
		};
		"/_authed/app": {
			id: "/_authed/app";
			path: "/app";
			fullPath: "/app";
			preLoaderRoute: typeof AuthedAppRouteImport;
			parentRoute: typeof AuthedRoute;
		};
		"/_authed/admin": {
			id: "/_authed/admin";
			path: "/admin";
			fullPath: "/admin";
			preLoaderRoute: typeof AuthedAdminRouteImport;
			parentRoute: typeof AuthedRoute;
		};
		"/api/setup-status/": {
			id: "/api/setup-status/";
			path: "/api/setup-status";
			fullPath: "/api/setup-status/";
			preLoaderRoute: typeof ApiSetupStatusIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/og/": {
			id: "/api/og/";
			path: "/api/og";
			fullPath: "/api/og/";
			preLoaderRoute: typeof ApiOgIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/manifest/": {
			id: "/api/manifest/";
			path: "/api/manifest";
			fullPath: "/api/manifest/";
			preLoaderRoute: typeof ApiManifestIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authed/reports/": {
			id: "/_authed/reports/";
			path: "/";
			fullPath: "/reports/";
			preLoaderRoute: typeof AuthedReportsIndexRouteImport;
			parentRoute: typeof AuthedReportsRoute;
		};
		"/_authed/app/": {
			id: "/_authed/app/";
			path: "/";
			fullPath: "/app/";
			preLoaderRoute: typeof AuthedAppIndexRouteImport;
			parentRoute: typeof AuthedAppRoute;
		};
		"/_authed/admin/": {
			id: "/_authed/admin/";
			path: "/";
			fullPath: "/admin/";
			preLoaderRoute: typeof AuthedAdminIndexRouteImport;
			parentRoute: typeof AuthedAdminRoute;
		};
		"/api/auth/$": {
			id: "/api/auth/$";
			path: "/api/auth/$";
			fullPath: "/api/auth/$";
			preLoaderRoute: typeof ApiAuthSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authed/app/new": {
			id: "/_authed/app/new";
			path: "/new";
			fullPath: "/app/new";
			preLoaderRoute: typeof AuthedAppNewRouteImport;
			parentRoute: typeof AuthedAppRoute;
		};
		"/_authed/app/$brand": {
			id: "/_authed/app/$brand";
			path: "/$brand";
			fullPath: "/app/$brand";
			preLoaderRoute: typeof AuthedAppBrandRouteImport;
			parentRoute: typeof AuthedAppRoute;
		};
		"/_authed/admin/workflows": {
			id: "/_authed/admin/workflows";
			path: "/workflows";
			fullPath: "/admin/workflows";
			preLoaderRoute: typeof AuthedAdminWorkflowsRouteImport;
			parentRoute: typeof AuthedAdminRoute;
		};
		"/_authed/admin/tools": {
			id: "/_authed/admin/tools";
			path: "/tools";
			fullPath: "/admin/tools";
			preLoaderRoute: typeof AuthedAdminToolsRouteImport;
			parentRoute: typeof AuthedAdminRoute;
		};
		"/_authed/accept-invitation/$invitationId": {
			id: "/_authed/accept-invitation/$invitationId";
			path: "/accept-invitation/$invitationId";
			fullPath: "/accept-invitation/$invitationId";
			preLoaderRoute: typeof AuthedAcceptInvitationInvitationIdRouteImport;
			parentRoute: typeof AuthedRoute;
		};
		"/api/v1/reports/": {
			id: "/api/v1/reports/";
			path: "/api/v1/reports";
			fullPath: "/api/v1/reports/";
			preLoaderRoute: typeof ApiV1ReportsIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/v1/prompts/": {
			id: "/api/v1/prompts/";
			path: "/api/v1/prompts";
			fullPath: "/api/v1/prompts/";
			preLoaderRoute: typeof ApiV1PromptsIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/v1/docs/": {
			id: "/api/v1/docs/";
			path: "/api/v1/docs";
			fullPath: "/api/v1/docs/";
			preLoaderRoute: typeof ApiV1DocsIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/v1/competitors/": {
			id: "/api/v1/competitors/";
			path: "/api/v1/competitors";
			fullPath: "/api/v1/competitors/";
			preLoaderRoute: typeof ApiV1CompetitorsIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/v1/brands/": {
			id: "/api/v1/brands/";
			path: "/api/v1/brands";
			fullPath: "/api/v1/brands/";
			preLoaderRoute: typeof ApiV1BrandsIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/plausible/event/": {
			id: "/api/plausible/event/";
			path: "/api/plausible/event";
			fullPath: "/api/plausible/event/";
			preLoaderRoute: typeof ApiPlausibleEventIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authed/app/$brand/": {
			id: "/_authed/app/$brand/";
			path: "/";
			fullPath: "/app/$brand/";
			preLoaderRoute: typeof AuthedAppBrandIndexRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/api/v1/tools/analyze": {
			id: "/api/v1/tools/analyze";
			path: "/api/v1/tools/analyze";
			fullPath: "/api/v1/tools/analyze";
			preLoaderRoute: typeof ApiV1ToolsAnalyzeRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/v1/reports/$reportId": {
			id: "/api/v1/reports/$reportId";
			path: "/api/v1/reports/$reportId";
			fullPath: "/api/v1/reports/$reportId";
			preLoaderRoute: typeof ApiV1ReportsReportIdRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/v1/prompts/$promptId": {
			id: "/api/v1/prompts/$promptId";
			path: "/api/v1/prompts/$promptId";
			fullPath: "/api/v1/prompts/$promptId";
			preLoaderRoute: typeof ApiV1PromptsPromptIdRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/v1/competitors/$competitorId": {
			id: "/api/v1/competitors/$competitorId";
			path: "/api/v1/competitors/$competitorId";
			fullPath: "/api/v1/competitors/$competitorId";
			preLoaderRoute: typeof ApiV1CompetitorsCompetitorIdRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/api/v1/brands/$brandId": {
			id: "/api/v1/brands/$brandId";
			path: "/api/v1/brands/$brandId";
			fullPath: "/api/v1/brands/$brandId";
			preLoaderRoute: typeof ApiV1BrandsBrandIdRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authed/reports/render/$reportId": {
			id: "/_authed/reports/render/$reportId";
			path: "/render/$reportId";
			fullPath: "/reports/render/$reportId";
			preLoaderRoute: typeof AuthedReportsRenderReportIdRouteImport;
			parentRoute: typeof AuthedReportsRoute;
		};
		"/_authed/app/$brand/visibility": {
			id: "/_authed/app/$brand/visibility";
			path: "/visibility";
			fullPath: "/app/$brand/visibility";
			preLoaderRoute: typeof AuthedAppBrandVisibilityRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/share-of-voice": {
			id: "/_authed/app/$brand/share-of-voice";
			path: "/share-of-voice";
			fullPath: "/app/$brand/share-of-voice";
			preLoaderRoute: typeof AuthedAppBrandShareOfVoiceRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/query-fan-out": {
			id: "/_authed/app/$brand/query-fan-out";
			path: "/query-fan-out";
			fullPath: "/app/$brand/query-fan-out";
			preLoaderRoute: typeof AuthedAppBrandQueryFanOutRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/opportunities": {
			id: "/_authed/app/$brand/opportunities";
			path: "/opportunities";
			fullPath: "/app/$brand/opportunities";
			preLoaderRoute: typeof AuthedAppBrandOpportunitiesRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/citations": {
			id: "/_authed/app/$brand/citations";
			path: "/citations";
			fullPath: "/app/$brand/citations";
			preLoaderRoute: typeof AuthedAppBrandCitationsRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/$": {
			id: "/_authed/app/$brand/$";
			path: "/$";
			fullPath: "/app/$brand/$";
			preLoaderRoute: typeof AuthedAppBrandSplatRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/api/plausible/js/script/": {
			id: "/api/plausible/js/script/";
			path: "/api/plausible/js/script";
			fullPath: "/api/plausible/js/script/";
			preLoaderRoute: typeof ApiPlausibleJsScriptIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authed/app/$brand/settings/": {
			id: "/_authed/app/$brand/settings/";
			path: "/settings";
			fullPath: "/app/$brand/settings/";
			preLoaderRoute: typeof AuthedAppBrandSettingsIndexRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/prompts/": {
			id: "/_authed/app/$brand/prompts/";
			path: "/prompts";
			fullPath: "/app/$brand/prompts/";
			preLoaderRoute: typeof AuthedAppBrandPromptsIndexRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/api/v1/prompts/$promptId/snapshot": {
			id: "/api/v1/prompts/$promptId/snapshot";
			path: "/snapshot";
			fullPath: "/api/v1/prompts/$promptId/snapshot";
			preLoaderRoute: typeof ApiV1PromptsPromptIdSnapshotRouteImport;
			parentRoute: typeof ApiV1PromptsPromptIdRoute;
		};
		"/_authed/app/$brand/settings/prompts": {
			id: "/_authed/app/$brand/settings/prompts";
			path: "/settings/prompts";
			fullPath: "/app/$brand/settings/prompts";
			preLoaderRoute: typeof AuthedAppBrandSettingsPromptsRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/settings/members": {
			id: "/_authed/app/$brand/settings/members";
			path: "/settings/members";
			fullPath: "/app/$brand/settings/members";
			preLoaderRoute: typeof AuthedAppBrandSettingsMembersRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/settings/llms": {
			id: "/_authed/app/$brand/settings/llms";
			path: "/settings/llms";
			fullPath: "/app/$brand/settings/llms";
			preLoaderRoute: typeof AuthedAppBrandSettingsLlmsRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/settings/competitors": {
			id: "/_authed/app/$brand/settings/competitors";
			path: "/settings/competitors";
			fullPath: "/app/$brand/settings/competitors";
			preLoaderRoute: typeof AuthedAppBrandSettingsCompetitorsRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/settings/brand": {
			id: "/_authed/app/$brand/settings/brand";
			path: "/settings/brand";
			fullPath: "/app/$brand/settings/brand";
			preLoaderRoute: typeof AuthedAppBrandSettingsBrandRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/prompts/edit": {
			id: "/_authed/app/$brand/prompts/edit";
			path: "/prompts/edit";
			fullPath: "/app/$brand/prompts/edit";
			preLoaderRoute: typeof AuthedAppBrandPromptsEditRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
		"/_authed/app/$brand/prompts/$promptId": {
			id: "/_authed/app/$brand/prompts/$promptId";
			path: "/prompts/$promptId";
			fullPath: "/app/$brand/prompts/$promptId";
			preLoaderRoute: typeof AuthedAppBrandPromptsPromptIdRouteImport;
			parentRoute: typeof AuthedAppBrandRoute;
		};
	}
}

interface AuthedAdminRouteChildren {
	AuthedAdminToolsRoute: typeof AuthedAdminToolsRoute;
	AuthedAdminWorkflowsRoute: typeof AuthedAdminWorkflowsRoute;
	AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute;
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
	AuthedAdminToolsRoute: AuthedAdminToolsRoute,
	AuthedAdminWorkflowsRoute: AuthedAdminWorkflowsRoute,
	AuthedAdminIndexRoute: AuthedAdminIndexRoute,
};

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(AuthedAdminRouteChildren);

interface AuthedAppBrandRouteChildren {
	AuthedAppBrandSplatRoute: typeof AuthedAppBrandSplatRoute;
	AuthedAppBrandCitationsRoute: typeof AuthedAppBrandCitationsRoute;
	AuthedAppBrandOpportunitiesRoute: typeof AuthedAppBrandOpportunitiesRoute;
	AuthedAppBrandQueryFanOutRoute: typeof AuthedAppBrandQueryFanOutRoute;
	AuthedAppBrandShareOfVoiceRoute: typeof AuthedAppBrandShareOfVoiceRoute;
	AuthedAppBrandVisibilityRoute: typeof AuthedAppBrandVisibilityRoute;
	AuthedAppBrandIndexRoute: typeof AuthedAppBrandIndexRoute;
	AuthedAppBrandPromptsPromptIdRoute: typeof AuthedAppBrandPromptsPromptIdRoute;
	AuthedAppBrandPromptsEditRoute: typeof AuthedAppBrandPromptsEditRoute;
	AuthedAppBrandSettingsBrandRoute: typeof AuthedAppBrandSettingsBrandRoute;
	AuthedAppBrandSettingsCompetitorsRoute: typeof AuthedAppBrandSettingsCompetitorsRoute;
	AuthedAppBrandSettingsLlmsRoute: typeof AuthedAppBrandSettingsLlmsRoute;
	AuthedAppBrandSettingsMembersRoute: typeof AuthedAppBrandSettingsMembersRoute;
	AuthedAppBrandSettingsPromptsRoute: typeof AuthedAppBrandSettingsPromptsRoute;
	AuthedAppBrandPromptsIndexRoute: typeof AuthedAppBrandPromptsIndexRoute;
	AuthedAppBrandSettingsIndexRoute: typeof AuthedAppBrandSettingsIndexRoute;
}

const AuthedAppBrandRouteChildren: AuthedAppBrandRouteChildren = {
	AuthedAppBrandSplatRoute: AuthedAppBrandSplatRoute,
	AuthedAppBrandCitationsRoute: AuthedAppBrandCitationsRoute,
	AuthedAppBrandOpportunitiesRoute: AuthedAppBrandOpportunitiesRoute,
	AuthedAppBrandQueryFanOutRoute: AuthedAppBrandQueryFanOutRoute,
	AuthedAppBrandShareOfVoiceRoute: AuthedAppBrandShareOfVoiceRoute,
	AuthedAppBrandVisibilityRoute: AuthedAppBrandVisibilityRoute,
	AuthedAppBrandIndexRoute: AuthedAppBrandIndexRoute,
	AuthedAppBrandPromptsPromptIdRoute: AuthedAppBrandPromptsPromptIdRoute,
	AuthedAppBrandPromptsEditRoute: AuthedAppBrandPromptsEditRoute,
	AuthedAppBrandSettingsBrandRoute: AuthedAppBrandSettingsBrandRoute,
	AuthedAppBrandSettingsCompetitorsRoute: AuthedAppBrandSettingsCompetitorsRoute,
	AuthedAppBrandSettingsLlmsRoute: AuthedAppBrandSettingsLlmsRoute,
	AuthedAppBrandSettingsMembersRoute: AuthedAppBrandSettingsMembersRoute,
	AuthedAppBrandSettingsPromptsRoute: AuthedAppBrandSettingsPromptsRoute,
	AuthedAppBrandPromptsIndexRoute: AuthedAppBrandPromptsIndexRoute,
	AuthedAppBrandSettingsIndexRoute: AuthedAppBrandSettingsIndexRoute,
};

const AuthedAppBrandRouteWithChildren = AuthedAppBrandRoute._addFileChildren(AuthedAppBrandRouteChildren);

interface AuthedAppRouteChildren {
	AuthedAppBrandRoute: typeof AuthedAppBrandRouteWithChildren;
	AuthedAppNewRoute: typeof AuthedAppNewRoute;
	AuthedAppIndexRoute: typeof AuthedAppIndexRoute;
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
	AuthedAppBrandRoute: AuthedAppBrandRouteWithChildren,
	AuthedAppNewRoute: AuthedAppNewRoute,
	AuthedAppIndexRoute: AuthedAppIndexRoute,
};

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(AuthedAppRouteChildren);

interface AuthedReportsRouteChildren {
	AuthedReportsIndexRoute: typeof AuthedReportsIndexRoute;
	AuthedReportsRenderReportIdRoute: typeof AuthedReportsRenderReportIdRoute;
}

const AuthedReportsRouteChildren: AuthedReportsRouteChildren = {
	AuthedReportsIndexRoute: AuthedReportsIndexRoute,
	AuthedReportsRenderReportIdRoute: AuthedReportsRenderReportIdRoute,
};

const AuthedReportsRouteWithChildren = AuthedReportsRoute._addFileChildren(AuthedReportsRouteChildren);

interface AuthedRouteChildren {
	AuthedAdminRoute: typeof AuthedAdminRouteWithChildren;
	AuthedAppRoute: typeof AuthedAppRouteWithChildren;
	AuthedReportsRoute: typeof AuthedReportsRouteWithChildren;
	AuthedAcceptInvitationInvitationIdRoute: typeof AuthedAcceptInvitationInvitationIdRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
	AuthedAdminRoute: AuthedAdminRouteWithChildren,
	AuthedAppRoute: AuthedAppRouteWithChildren,
	AuthedReportsRoute: AuthedReportsRouteWithChildren,
	AuthedAcceptInvitationInvitationIdRoute: AuthedAcceptInvitationInvitationIdRoute,
};

const AuthedRouteWithChildren = AuthedRoute._addFileChildren(AuthedRouteChildren);

interface ApiV1PromptsPromptIdRouteChildren {
	ApiV1PromptsPromptIdSnapshotRoute: typeof ApiV1PromptsPromptIdSnapshotRoute;
}

const ApiV1PromptsPromptIdRouteChildren: ApiV1PromptsPromptIdRouteChildren = {
	ApiV1PromptsPromptIdSnapshotRoute: ApiV1PromptsPromptIdSnapshotRoute,
};

const ApiV1PromptsPromptIdRouteWithChildren = ApiV1PromptsPromptIdRoute._addFileChildren(
	ApiV1PromptsPromptIdRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	AuthedRoute: AuthedRouteWithChildren,
	AuthForgotPasswordRoute: AuthForgotPasswordRoute,
	AuthLoginRoute: AuthLoginRoute,
	AuthLogoutRoute: AuthLogoutRoute,
	AuthRegisterRoute: AuthRegisterRoute,
	AuthResetPasswordRoute: AuthResetPasswordRoute,
	ApiAuthSplatRoute: ApiAuthSplatRoute,
	ApiManifestIndexRoute: ApiManifestIndexRoute,
	ApiOgIndexRoute: ApiOgIndexRoute,
	ApiSetupStatusIndexRoute: ApiSetupStatusIndexRoute,
	ApiV1BrandsBrandIdRoute: ApiV1BrandsBrandIdRoute,
	ApiV1CompetitorsCompetitorIdRoute: ApiV1CompetitorsCompetitorIdRoute,
	ApiV1PromptsPromptIdRoute: ApiV1PromptsPromptIdRouteWithChildren,
	ApiV1ReportsReportIdRoute: ApiV1ReportsReportIdRoute,
	ApiV1ToolsAnalyzeRoute: ApiV1ToolsAnalyzeRoute,
	ApiPlausibleEventIndexRoute: ApiPlausibleEventIndexRoute,
	ApiV1BrandsIndexRoute: ApiV1BrandsIndexRoute,
	ApiV1CompetitorsIndexRoute: ApiV1CompetitorsIndexRoute,
	ApiV1DocsIndexRoute: ApiV1DocsIndexRoute,
	ApiV1PromptsIndexRoute: ApiV1PromptsIndexRoute,
	ApiV1ReportsIndexRoute: ApiV1ReportsIndexRoute,
	ApiPlausibleJsScriptIndexRoute: ApiPlausibleJsScriptIndexRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
		config: Awaited<ReturnType<typeof startInstance.getOptions>>;
	}
}
