export {
	type FeatureKey,
	type CompetitorCategory,
	type Competitor,
	type FeatureDefinition,
	type FeatureCategory,
	FEATURE_CATEGORIES,
	ALL_FEATURE_KEYS,
	ELMO_FEATURES,
	CATEGORY_LABELS,
	LOW_DR_THRESHOLD,
	isLowDR,
	getFeatureLabel,
	getFeatureDescription,
	getScreenshotUrl,
} from "./types";

export {
	competitors,
	sortedCompetitors,
	getCompetitorBySlug,
	getComparisonSlug,
	getPopularityRank,
	getPopularityGrade,
} from "./data";

export { getComparisonFaqs, getComparisonVerdict } from "./content";

export {
	isIndexed,
	indexedCompetitors,
	getAlternatives,
	comparePairCompetitors,
	comparePairs,
	comparePairSlug,
	getComparePair,
	compareSets,
	compareSetSlug,
	getCompareSet,
	getSetVerdict,
	getSetFaqs,
	getCompareEntry,
	getCompareVerdict,
	getCompareFaqs,
	FEATURE_SLUGS,
	getFeatureKeyBySlug,
	toolsWithFeature,
	indexableFeatureKeys,
	MIN_TOOLS_FOR_FEATURE_PAGE,
	CATEGORY_SLUGS,
	CATEGORY_HEADINGS,
	getCategoryBySlug,
	toolsInCategory,
	indexableCategories,
	openSourceTools,
	getAlternativesVerdict,
	getAlternativesFaqs,
	getPairVerdict,
	getPairFaqs,
	getFeatureVerdict,
	getFeatureFaqs,
	getCategoryVerdict,
	getCategoryFaqs,
	getCategoryElmoPitch,
} from "./directory";
